### ISSUE TITLE
dark themes error

### ISSUE THREAD

**Issue by Chrede88** [sourcethemes/academic-kickstart#115]
I'm getting an error when trying to use a dark theme.
Tried all "build-in" dark themes: dark, mr_robot and apogee. All give me the same error.
This is the error I get:
```
"partials/functions/parse_theme.html" at <$theme.light.background>: can't evaluate field background in type interface {}
```
If I set the theme setting `light = true` in any of the dark themes, the site is compiled.

Any idea?

I've the latest version of academic-kickstart (6dfec63) and I'm running Hugo version 0.74.3.

Christian

**Comment by gcushen** [comment]
Thanks for reporting this! It should be fixed now in the latest master version of Academic.
