### ISSUE TITLE
Problems with Latex support

### ISSUE THREAD

**Issue by JayanthRR** [sourcethemes/academic-kickstart#2]
Latex processing seems very inconsistent. It doesn't render simple equations at times. This is just one example.

This is inline: $\mathbf{y} = \mathbf{X}\boldsymbol\beta + \boldsymbol\varepsilon$
The system has the form $x = f_{k}(x_{k}, u_{k}, w_{k})$ 

![issue](https://user-images.githubusercontent.com/23566173/37191449-b168a560-232d-11e8-9948-de71b36378bf.png)

**Comment by gcushen** [comment]
Have you read the Academic documentation on how to use LaTeX in Academic?

**Comment by JayanthRR** [comment]
Thanks, I figured it out that the syntax is slightly different from standard LaTeX. I needed to add a leading \ before every _

`The system has the form $x = f\_{k}(x\_{k}, u\_{k}, w\_{k})$`

**Comment by JayanthRR** [comment]
@gcushen I have another quick question. Is there any restriction on the type/size of images while attaching in Academic? I find that images of some resolution work well, and some others of a different resolution do not get attached. Is there some special care that we need to take while attaching images.

![issue2](https://user-images.githubusercontent.com/23566173/37246070-6019d4ce-2470-11e8-9ed8-32d924655af1.png)
