### ISSUE TITLE
Unable to view website with hugo

### ISSUE THREAD

**Issue by akuznetso** [sourcethemes/academic-kickstart#27]
When trying to run hugo server from the cloned directory, I get message:

Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Config File "config" Not Found in "[/home/akuznetsa/Downloads/My_Website]")

There is indeed to config file in the directory. How to fix?

**Comment by gcushen** [comment]
Please post on the forums for support issues.
