### ISSUE TITLE
Unable to locate template for shortcode "staticref" in page "home/about.md"

### ISSUE THREAD

**Issue by JayanthRR** [sourcethemes/academic-kickstart#3]
Hello,

I ran into a problem today while trying to deploy hugo on github pages. The deployment was working all fine until I ran the following command. 
`hugo --cleanDestinationDir`

Then I got an error message saying git crashed. Once I removed the .git/index.lock file and re ran hugo, I got the following error
`Building sites … ERROR 2018/03/10 19:23:48 Unable to locate template for shortcode "staticref" in page "home/about.md"`

I feel I shouldn't have included `--cleanDestinationDir` as it was working fine before when I just ran `hugo`. I do not know how to resolve it now.

**Comment by gcushen** [comment]
Since this is related to Hugo's implementation of `cleanDestinationDir`, please post on the Hugo forums for support. Note that the option is briefly documented by the Hugo team here: https://gohugo.io/commands/hugo/

**Comment by JayanthRR** [comment]
True that `cleanDestinationDir` is not required, I was just trying it out. I posted on Hugo forums btw. Thanks.
