### ISSUE TITLE
Consider the creation of tags for versioning.

### ISSUE THREAD

**Issue by armfazh** [sourcethemes/academic-kickstart#33]
It would be great to use git tags/releases for versioning this repo.

**Comment by gcushen** [comment]
What would be the purpose? This repo is intended only for creating sites.

If the purpose is to use as an example when upgrading your site, then the full example site is already tagged with versions and is perhaps much more useful as it shows the changes to content frontmatter too: https://github.com/gcushen/hugo-academic/tree/master/exampleSite . Pretty much the only file not in the example site that does exist in this repo is the Netlify config file, where the Hugo version is updated to be compatible with new releases of Academic.

**Comment by armfazh** [comment]
got it, it makes sense to me. Thanks for the explanation.
