### ISSUE TITLE
altmetrics badge

### ISSUE THREAD

**Issue by xvazquezc** [sourcethemes/academic-kickstart#34]
Hi there,

I'm trying to modify the theme code to display the Altmetrics badge on each paper to get something like [this](https://astrobiomike.github.io/research/). So far I was able to do it (sort of) in the publication pages by modifying the `academic-admin` code so it adds the html code at the end of each `index.md` if there is a DOI available.

I'm pretty sure it's not the best way so I'm wondering which files dictate the way the citations are styled in the `Publication` page and which one sets the outline for each single publication page (where the abstract appears).

Cheers,
Xabi

**Comment by gcushen** [comment]
Please use the [forums](https://discourse.gohugo.io/c/themes) or [chat](https://spectrum.chat/academic) for questions/troubleshooting. Also refer to the [Academic](https://sourcethemes.com/academic/docs/) and [Hugo](https://gohugo.io/documentation/) Documentation.
