### ISSUE TITLE
Embedding html not working 

### ISSUE THREAD

**Issue by cvanelteren** [sourcethemes/academic-kickstart#36]
According to the docs one can host jupyter notebooks as htmls or markdown. However, embedding html in an iframe results in 404 error. 
```html
    +++
    title = ""

    date = 2019-07-06T14:00:00

    summary = ""
    +++

    <iframe
    src = "./test.html"
    width = "90%"
    height = "1000px"
    style = "border:none">
    This is not the site you are looking for
    </iframe>
```

Embedding a site on the web works fine. The path is done according to the docs, am I doing something wrong that I am not aware of?

**Comment by gcushen** [comment]
Please use the [forums](https://discourse.gohugo.io/c/themes) or [chat](https://spectrum.chat/academic) for questions/troubleshooting. There are already a lot of forum threads on embedding files using iframes.
