### ISSUE TITLE
Whitespace issue

### ISSUE THREAD

**Issue by prakhargurunani** [sourcethemes/academic-kickstart#42]
Hi @gcushen :smile:!
I am getting some weird whitespace at -<br>
* Last updated on Aug 13, 2019 • 3 min read • `whitespace here` • Non-Tech
* Last updated on Aug 13, 2019 • 2 min read • `whitespace here` • Tech
* Last updated on Aug 13, 2019 • 3 min read • `whitespace here` • Tech
<br>

`Link`: https://www.prakhargurunani.com/#posts
![Screenshot (61)](https://user-images.githubusercontent.com/43035576/63090062-a9a9c600-bf77-11e9-9584-18c7871e7d7b.png)

**Comment by gcushen** [comment]
Please use the [forums](https://discourse.gohugo.io/c/themes) or [chat](https://spectrum.chat/academic) for questions/troubleshooting. Also refer to the [Academic](https://sourcethemes.com/academic/docs/) and [Hugo](https://gohugo.io/documentation/) Documentation.

In this case, it looks like you may have Disqus comment count enabled in which case you can try disabling it in `params.toml` under Comments section.
