### ISSUE TITLE
Logo - Required dimensions?

### ISSUE THREAD

**Issue by ReneHeim** [sourcethemes/academic-kickstart#51]
Dear Georg,

I am currently migrating from github pages to the hugo academic theme. I totally enjoy the experience. However, when trying to include a logo instead of a title, the image is never displayed. Only a "broken image" icon. I am using a "logo.png" and it is saved in .\static\img

What could I do wrong? Are there any requirements regarding dimension?

Thanks a lot for your amazing theme. 

René

**Comment by gcushen** [comment]
See https://github.com/gcushen/hugo-academic/blob/master/.github/support.md .

The repo for the Academic documentation provides an example of using the logo.
