### ISSUE TITLE
Using as a template does not bring clone `/themes` 

### ISSUE THREAD

**Issue by jrwrigh** [sourcethemes/academic-kickstart#61]
I used the "Use this template" button on the repository, but the operation does not transport the "themes" directory with it. So running `git submodule update --init --recursive` does not actually do anything. 

Is it possible to make GitHub keep the `/themes` directory in tact when using the template feature?

**Comment by gcushen** [comment]
Github's template feature is relatively new and it appears that Git Submodules are currently unsupported by the feature. Github's docs for this feature are also currently [lacking](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).

Therefore, I've removed Github's *Use Template* option from this repo, and recommend following that standard installation steps for Academic at https://sourcethemes.com/academic/docs/install/
