### ISSUE TITLE
Experience timeline re-ordering

### ISSUE THREAD

**Issue by astrochun** [sourcethemes/academic-kickstart#62]
This is purely UX related, but I noticed that with the Experience timeline, items are sorted by starting date.  This means that long-term positions that are still active shows up lower in the list.  While I see that on-going positions are solid bullet points, I don't think this is easily apparent for general users.

Would it be possible to group by date_end = "" first and then sort based on past appointments?

**Comment by gcushen** [comment]
This is the template, not the actual theme. Feel free to discuss your feature request in the community chat or as an issue in the Academic repo - if I recall, if you search there, you might find similar discussions.
