### ISSUE TITLE
crawling is blocked

### ISSUE THREAD

**Issue by taiebat** [sourcethemes/academic-kickstart#73]
I have made my website and deployed it on github pages: taiebat.github.io
Noticed that after two months, it has not been indexed by google. Checking with a third party website, I learned that my website blocks crawling. Can you please give me some insights on how to allow robots to crawl the website? I cannot find where to look for robots.txt or the necessary tags.

Thanks!

**Comment by gcushen** [comment]
These issues are for bug reports and feature requests. For support, see https://github.com/gcushen/hugo-academic/blob/master/.github/support.md
