### ISSUE TITLE
Different behavior from demo for day to night mode

### ISSUE THREAD

**Issue by eduardomachuca** [sourcethemes/academic-kickstart#76]
Using Hugo v0.67.0/extended, Academic version = "4.8.0", on Debian 10 xfce and Chrome Version 80.0.3987.132.

- If on params.toml I set day_night = true then the site shows the sun icon.
- If I click on it, the icon changes to a moon but the page doesn't go dark.
- I have to click once more on the moon for the site to go dark, but then the icon changed from a moon to a palette icon.
- An I have to click again on the palette icon to go from dark to light mode (sun icon).

This is different from the _demo_ where the page only show a palette icon and on hover it shows a drop-down menu with Light, Dark and Automatic options. However, clicking on any of the options doesn't change the icon, which remains as a palette. Still, the site immediately goes into the selected mode.

Don't understand the code restrictions, but wouldn't it be better the following behavior?:

1. Set day_night = true in params.toml
2. Site starts with the sun icon (light mode)
3. If the user clicks on the sun icon, it changes to a moon and the site immediately goes into dark mode.
4. If the user click on the moon, the icon changes to a sun and the site immediately goes into light mode.

Thanks,

**Comment by gcushen** [comment]
If you update to the master version, you'll pick up the changes seen in the [latest demo](https://academic-demo.netlify.com/) which make the options explicit and more intuitive to use.

**Comment by gcushen** [comment]
Also, this is related to Academic and not Kickstart. In the Academic repo, you can search for the thread where this topic was discussed.
