### ISSUE TITLE
bugs in authors content

### ISSUE THREAD

**Issue by pangxueyu233** [sourcethemes/academic-kickstart#83]
hi, 
Recently, we want bulid a lab website based on academic theme. But when I build in local, authors contents always keep some problems. every time when I do ``` hugo server``` and log in http://localhost:1313/ to check the authors information. sometimes it show that 
![image](https://user-images.githubusercontent.com/40414477/81249786-19a23400-9052-11ea-8f74-fa08c1cc56ec.png)
which is we want to see 
but some times it became that
![image](https://user-images.githubusercontent.com/40414477/81249906-5ff79300-9052-11ea-997c-868424e1d0c8.png)
which we didn't want to see.
Can you help us work it out? whether it would be a bug for unstable version of academic theme?
Thanks a lot

**Comment by gcushen** [comment]
Closing as unrelated to this repo and posting duplicates - https://github.com/gcushen/hugo-academic/issues/1687
