### ISSUE TITLE
Can not update my webpage

### ISSUE THREAD

**Issue by wzjin2017** [sourcethemes/academic-kickstart#9]
Hi, thanks for building this simple tool for building a webpage.  Actually, I ran into this problem after getting started. The first few commits on GitHub were successful and I managed to edit some features based on the template. But later when I I tried to replace it with my information in **content/home/about**, it was successfully committed but the webpage didn't synchronize with it. 

Could you help me with this?

**Comment by gcushen** [comment]
These issues are for feature suggestions. For support, please use the [support forum](http://discuss.gohugo.io/). Thanks.
